<?php

namespace W3build\MediaBundle\Repository;

use Doctrine\ORM\EntityManager;
use W3build\MediaBundle\Entity\Image;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository
{

    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function find($id){
        $queryBuilder = $this->entityManager->createQueryBuilder();
        $queryBuilder->select('image')
            ->from(Image::ENTITY_NAME, 'image')
            ->where('image.id = :id')
            ->setParameter('id', $id);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }

    public function save(Image $image){
        $this->entityManager->persist($image);
        $this->entityManager->flush();
    }

}
